#!/bin/sh
cd() {
    [[ -f $1 ]] && 1="$1:h" # if you 'cd some/file' it's like 'cd some/'
    builtin cd "$@" || return
    local lspp=~/.../src/ls--/ls++
    if [ -x $lspp ]; then
        if perl -MTerm::ExtendedColor -e 1 >/dev/null 2>&1; then
            $lspp || true
        else
            ls -l
            [ -n "$WANT_ALL" ] &&
                echo "Needs: cpanm Term::ExtendedColor" || true
        fi
    else
        ls -l
        [ -n "$WANT_ALL" ] && echo "Not executable: $lspp" || true
    fi
}
